# Generated by Django 3.2 on 2023-03-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField()),
                ('profile_picture', models.ImageField(default='default_avatar.png', upload_to='trainer_avatars/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.specialization')),
            ],
        ),
    ]
