# Generated by Django 3.2 on 2023-03-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='profile_picture',
            new_name='profile_avatar',
        ),
    ]
