# Generated by Django 3.2 on 2023-02-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packdetail',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
