# Generated by Django 3.2 on 2023-02-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_packdetail_included'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
    ]
